### PR TITLE
fix spell textures in TWW

### PR DESCRIPTION
**Pull request by ntowle**

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm, is this `GetSpellTexture` is available in Classic/SoM clients?

**Comment by ntowle** [comment]
C_Spell.GetSpellTexture is available in TWW, GetSpellTexture is available in Era/Cata/Dragonflight.

**Comment by silverwind** [comment]
Ah i overlooked that you are aliasing the function. Could you move that inline please into a `if C_Spell and C_Spell.GetSpellTexture then ...` block? I find that more readable.

**Comment by silverwind** [comment]
Thanks, I will give this a test later before releasing.

**Pull request merged**
