### PR TITLE
Added CurrencyID

### PR DESCRIPTION
**Pull request by tiker**
Added CurrencyIDs to the CurrencyID tooltip window when viewing from a link.

### CODE REVIEW

**Comment by silverwind** [comment]
I trust you this works, as I can't test it :)

Will do a release later today.

**Comment by tiker** [comment]
This works when clicking the currency link in chat.  It does not work when moving the mouse over the icon in the character / currency frame (yet).  I just found this mod and it's much cleaner than the one I had been using.

I plan on submitting a few more patches for missions, garrison followers, etc. when I get a chance.  :)

Thanks.

**Comment by silverwind** [comment]
Yeah, `onSetHyperlink` is only used for static tooltips. For the other tooltips, I bet this is used:

http://wowprogramming.com/docs/widgets/GameTooltip/SetCurrencyByID

I think you should be able to hook it like this:

https://github.com/silverwind/idTip/blob/master/core.lua#L58-L61

I'll hold up the relase till that is solved :)

**Comment by tiker** [comment]
I was actually just playing with that but it does not seem to work:

This does not display anything in the chat window. it should at least show "hi" to indicate the hook is working but it's not.

-- Currencies
hooksecurefunc(GameTooltip, "SetCurrencyByID", function(self, ...)
	DEFAULT_CHAT_FRAME:AddMessage(GREEN_FONT_COLOR_CODE.."TEST: |r"..tostring(...))
	DEFAULT_CHAT_FRAME:AddMessage(GREEN_FONT_COLOR_CODE.."TEST: |r"..tostring("hi"))
-- does not seem to fire...
    if id then addLine(self, id, types.currency) end
end)

**Comment by silverwind** [comment]
Maybe it's

http://wowprogramming.com/docs/widgets/GameTooltip/SetCurrencyTokenByID

**Comment by tiker** [comment]
SetCurrenyTokenByID doesn't seem to fire either.  I've got a couple of ideas but it'll be a few hours before I get to trying them out.  I'll let you know when I've got it figured out.

**Comment by silverwind** [comment]
Alright. There's also the possibilty it's not `GameToolip` at all, you might have to look through `FrameXML`.

**Comment by tiker** [comment]
That's one thing I've started doing.  I've also got another mod that is modifying the tool tip frame that appears so I'll look and see how that mod is doing it.  :)

**Pull request merged**
